#!/bin/sh
#PS1='\033[?17;0;127c'
#mount -t nfs -o rsize=32768,wsize=32768,intr 192.168.10.1:/data/video /media

clear
OMXPLAYER="./omxplayer.bin"
FBSET="/usr/sbin/fbset"

if [ -e /usr/local/bin/omxplayer.bin ]; then
  OMXPLAYER="/usr/local/bin/omxplayer.bin"
elif [ -e /usr/bin/omxplayer.bin ]; then
  OMXPLAYER="/usr/bin/omxplayer.bin"
else
  OMXPLAYER="./omxplayer.bin"
fi

if [ -e /usr/local/bin/omxplayer.bin ]; then
  export LD_LIBRARY_PATH=/opt/vc/lib:/usr/local/lib:$LD_LIBRARY_PATH 
elif [ -e /usr/lib ]; then
  export LD_LIBRARY_PATH=/opt/vc/lib:/usr/lib:$LD_LIBRARY_PATH 
else
  export LD_LIBRARY_PATH=/usr/local/src/omxplayer/ffmpeg_compiled/usr/local/lib:/opt/vc/lib:$LD_LIBRARY_PATH
fi

XRES=1920
YRES=1080


if [ -e $FBSET ]; then
  echo 0 >  /sys/class/vtconsole/vtcon1/bind
  fbset -xres 1 -yres 1
fi

$OMXPLAYER "$@"

if [ -e $FBSET ]; then
  fbset -xres ${XRES} -yres ${YRES}
  echo 1 >  /sys/class/vtconsole/vtcon1/bind
fi
